"""Extract a varied sample of REAL books from the generated library into the frontend
story-data files, so the storybook 'Play' stories use the CURRENT padded (7-row) reveal
format the renderer expects. Run from math/ root:
    env/Scripts/python.exe games/prism_path/_extract_story_books.py
"""
import json
import os
import random

import zstandard

random.seed(7)
HERE = os.path.dirname(os.path.abspath(__file__))
LIB = os.path.join(HERE, "library", "publish_files")
DST = os.path.normpath(os.path.join(HERE, "..", "..", "..", "frontend", "apps", "prism-path", "src", "stories", "data"))


def read_books(name):
    with open(os.path.join(LIB, name), "rb") as f:
        data = zstandard.ZstdDecompressor().stream_reader(f).read()
    return [json.loads(line) for line in data.split(b"\n") if line.strip()]


def sample(books, n):
    return books if len(books) <= n else random.sample(books, n)


def write_ts(name, books):
    with open(os.path.join(DST, name), "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by _extract_story_books.py — real books from math/library\n")
        f.write("// (padded 7-row reveals; do not hand-edit, regenerate instead).\n")
        f.write("export default ")
        json.dump(books, f)
        f.write(";\n")


base = read_books("books_base.jsonl.zst")
bonus = read_books("books_bonus.jsonl.zst")
superb = read_books("books_super.jsonl.zst")
out_base = sample(base, 400)
out_bonus = sample(bonus, 120)
out_super = sample(superb, 80)
write_ts("base_books.ts", out_base)
write_ts("bonus_books.ts", out_bonus)
write_ts("super_books.ts", out_super)

rev = next(e for e in out_base[0]["events"] if e["type"] == "reveal")
print("wrote base", len(out_base), "bonus", len(out_bonus))
print("base reveal rows/reel:", [len(c) for c in rev["board"]])
print("sample cell:", rev["board"][0][0])
print("base payoutMultipliers (first 10):", [b.get("payoutMultiplier") for b in out_base[:10]])
